from abc import ABC, abstractmethod
from typing import Any, Optional


class IApiService(ABC):
    # --- Utilisateurs ---
    @abstractmethod
    def get_all_users(self) -> Any: ...

    @abstractmethod
    def get_user(self, iduser: int) -> Any: ...

    @abstractmethod
    def create_user(self, data: dict) -> Any: ...

    @abstractmethod
    def update_user(self, iduser: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_user(self, iduser: int) -> Any: ...

    # --- Images utilisateur (table imageuser) ---
    @abstractmethod
    def get_all_user_images(self) -> Any: ...

    @abstractmethod
    def get_user_image(self, idimage: int) -> Any: ...

    @abstractmethod
    def get_user_images_by_user(self, iduser: int) -> Any: ...

    @abstractmethod
    def create_user_image(self, data: dict) -> Any: ...

    @abstractmethod
    def update_user_image(self, idimage: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_user_image(self, idimage: int) -> Any: ...

    # --- Historique ---
    @abstractmethod
    def get_all_history(self) -> Any: ...

    @abstractmethod
    def get_historique(self, historique_id: int) -> Any: ...

    @abstractmethod
    def create_historique(self, data: dict) -> Any: ...

    @abstractmethod
    def delete_historique(self, historique_id: int) -> Any: ...

    # --- Conversations ---
    @abstractmethod
    def get_last_100_conversations(self) -> Any: ...

    @abstractmethod
    def get_all_conversations(self, date_from=None, date_to=None) -> Any: ...

    @abstractmethod
    def get_conversation(self, idconv: int) -> Any: ...

    @abstractmethod
    def create_conversation(self, data: dict) -> Any: ...

    @abstractmethod
    def update_conversation(self, idconv: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_conversation(self, idconv: int) -> Any: ...

    # --- Notes ---
    @abstractmethod
    def get_all_notes(self) -> Any: ...

    @abstractmethod
    def get_note(self, note_id: int) -> Any: ...

    @abstractmethod
    def create_note(self, data: dict) -> Any: ...

    @abstractmethod
    def update_note(self, note_id: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_note(self, note_id: int) -> Any: ...

    @abstractmethod
    def modify_note_etat(self, note_id: int, etat: bool) -> Any: ...

    # --- Settings ---
    @abstractmethod
    def get_settings(self) -> Any: ...

    @abstractmethod
    def modify_settings(self, settings_data: dict) -> Any: ...

    # --- Activités (table note) ---
    @abstractmethod
    def get_all_activities(self) -> Any: ...

    @abstractmethod
    def get_activity(self, activity_id: int) -> Any: ...

    @abstractmethod
    def create_activity(self, data: dict) -> Any: ...

    @abstractmethod
    def update_activity(self, activity_id: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_activity(self, activity_id: int) -> Any: ...

    # --- Informations personnelles ---
    @abstractmethod
    def get_personal_info(self) -> Any: ...

    @abstractmethod
    def get_personal_info_by_user(self, iduser: int) -> Any: ...

    @abstractmethod
    def add_personal_info(self, info_data: dict) -> Any: ...

    @abstractmethod
    def update_personal_info(self, info_id: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_personal_info(self, info_id: int) -> Any: ...

    # --- Accompagnement ---
    @abstractmethod
    def get_all_accompagnements(self) -> Any: ...

    @abstractmethod
    def get_accompagnement(self, accompagnement_id: int) -> Any: ...

    @abstractmethod
    def get_accompagnements_by_user(self, iduser: int) -> Any: ...

    @abstractmethod
    def create_accompagnement(self, data: dict) -> Any: ...

    @abstractmethod
    def update_accompagnement(self, accompagnement_id: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_accompagnement(self, accompagnement_id: int) -> Any: ...

    # --- Authentification ---
    @abstractmethod
    def login(self, emailclient: str, motdepasse: str) -> Optional[dict]: ...

    @abstractmethod
    def get_authentification(self, idproduit: int) -> Any: ...

    @abstractmethod
    def list_authentifications(self) -> Any: ...

    @abstractmethod
    def create_authentification(self, data: dict) -> Any: ...

    @abstractmethod
    def update_authentification(self, idproduit: int, data: dict) -> Any: ...

    @abstractmethod
    def delete_authentification(self, idproduit: int) -> Any: ...

    # --- n8n ---
    @abstractmethod
    def send_to_n8n(self, payload: dict) -> Any: ...

    # --- Reconnaissance faciale ---
    @abstractmethod
    def identify_face(self, image_bytes: bytes) -> str: ...

    # --- Power on/off ---
    @abstractmethod
    def power_off(self) -> Any: ...

    @abstractmethod
    def power_on(self) -> Any: ...

    # --- Audio (Azure Speech) ---
    @abstractmethod
    def speech_to_text(self, audio_bytes: bytes) -> Any: ...

    @abstractmethod
    def text_to_speech(self, text: str, voice_name=None) -> Any: ...

    @abstractmethod
    def audio_to_n8n_to_audio(self, audio_bytes: bytes, voice_name=None, extra_text=None) -> Any: ...

    # --- Gemini keywords ---
    @abstractmethod
    def generate_robot_name_keywords(self) -> Any: ...
